train:
  # picked trial 45
  ner:
    output_dir: "ner"
    save_strategy: "no"
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    num_train_epochs: 3
    warmup_ratio: 0.0
    weight_decay: 0.0
    learning_rate: 5.0e-05
    logging_steps: 10000
    load_best_model_at_end: True
    report_to: "wandb"

  re: # picked trial 1
    output_dir: "re"
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    save_total_limit: 1
    logging_steps: 10000
    save_strategy: "no"
    learning_rate: 5.0e-05
    num_train_epochs: 3
    warmup_ratio: 0.0
    weight_decay: 0.0
    report_to: "wandb"
