train:
  ner:
    output_dir: "ner"
    evaluation_strategy: "epoch"
    save_strategy: "epoch"
    save_total_limit: 6
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    num_train_epochs: 6
    warmup_ratio: 0.0
    weight_decay: 0.0
    learning_rate: 5.0e-05
    load_best_model_at_end: True
    report_to: "wandb"

  re:
    output_dir: "re"
    evaluation_strategy: "epoch"
    save_strategy: "epoch"
    save_total_limit: 6
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    learning_rate: 5.0e-05
    num_train_epochs: 6
    warmup_ratio: 0.0
    weight_decay: 0.0
    load_best_model_at_end: True
    report_to: "wandb"
